/*
* qianqians
* 2015-10-9
*/
#include "glextARB.h"

PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog = 0;
PFNGLGETSHADERIVPROC glGetShaderiv = 0;
PFNGLGETATTRIBLOCATIONPROC glGetAttribLocation = 0;
PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer = 0;
PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray = 0;
PFNGLBUFFERDATAPROC glBufferData = 0;
PFNGLBINDBUFFERPROC glBindBuffer = 0;
PFNGLGENBUFFERSPROC glGenBuffers = 0;
PFNGLGENVERTEXARRAYSPROC glGenVertexArrays = 0;
PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays = 0;
PFNGLLINKPROGRAMPROC glLinkProgram = 0;
PFNGLDETACHSHADERPROC glDetachShader = 0;
PFNGLATTACHSHADERPROC glAttachShader = 0;
PFNGLDELETESHADERPROC glDeleteShader = 0;
PFNGLCOMPILESHADERPROC glCompileShader = 0;
PFNGLSHADERSOURCEPROC glShaderSource = 0;
PFNGLCREATESHADERPROC glCreateShader = 0;
PFNGLUSEPROGRAMPROC glUseProgram = 0;
PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog = 0;
PFNGLGETPROGRAMIVPROC glGetProgramiv = 0;
PFNGLCREATEPROGRAMPROC glCreateProgram = 0;
PFNGLBINDVERTEXARRAYPROC glBindVertexArray = 0;
PFNGLVALIDATEPROGRAMPROC glValidateProgram = 0;
PFNGLACTIVETEXTUREPROC glActiveTexture = 0;